default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: task1_development

test:
  <<: *default
  database: task1_test

production:
  <<: *default
  database: task1_production
  username: task1
  password: <%= ENV['TASK1_DATABASE_PASSWORD'] %>
